### PR TITLE
Misc fixes to MovieInfo

### PR DESCRIPTION
**Pull request by Nadahar**
Originally I was only going to update the plugin to not use deprecated UMS methods. Once that was done, and a couple of null exceptions was dealth with, I discovered that there was some serious memory leaking going on (My UMS would eat 3.5 GB in one minute if I browsed some movie info from a renderer).

To try to find the memory leak, I had to do a lot of restructuring (I'm sorry, but I had a hard time reading the code). I never found the exact reason, although I do suspect there's some syncronization issues that need to be fixed in UMS that's the reason, but I did a lot of small (and some a bit bigger) fixes and optimalizations hoping that I would get lucky and "touch" whatever was causing the memory leak. I'm not sure what did what, but I haven't seen the same memory grabbing on later tests.

The list of changes is:
* Replaced deprecated methods
* Removed unused methods
* Removed unused variables
* Removed unused imports
* Fixed a NullException in ```IMDBPlugin.lookForMovieID()```
* Rewrote ```IMDBPlugin.getCast()``` to match new list structure and to better handle actor pictures (resizing pictures instead of very small pictures with large padded frame)
* Made ```FileMovieInfoVirtualFolder``` constructors consistent in variable initialization
* Fixed a NullException in ```FileMovieInfoVirtualFolder.clean()```
* Fixed a bug in ```FileMovieInfoVirtualFolder.getMovienameFromFilename()``` rendering filter functionality useless
* Updated ```MOVIEINFO.conf``` default to match that of the hardcoded defaults
* Made a class/type for Cast (actor, character, model) for better type safety and control
* Made sure configuration is read one place (```MoveInfoConfiguration```) and one time instead of multiple times in several classes. Renamed and used existing class ```MovieInfoCfg``` that was hardly used
* Changed formatting for better readability in various places
* Removed autogenerated ```TODO```'s
* Added consistent logging with ```{MovieInfo}``` tag and replaced all prints to stdout with logging
* Added or improved exception handling in various places
* Renaming many variables for better readability
* Made clearing of global variables once they are displayed and no longer needed
* Moved ```MovieDB.add``` in ```FileMovieInfoVirtualFolder.gather()``` so that it only stores information if any is found
* Localized some variables that didn't need to be global
* Rewrote ```FileMovieInfoVirtualFolder.resolve()``` to only run once, to avoid listing info multiple times

### CODE REVIEW

**Comment by SubJunk** [comment]
Cool. This has needed an update for a while. What do you think @SharkHunter ?

**Comment by SharkHunter** [comment]
Yeah it has. The code isn't originally mine so I have no objections to naything :)

**Comment by SubJunk** [comment]
@SharkHunter would you be able to update it in our plugin repository so users can get it?

**Comment by SharkHunter** [comment]
yeah sometime during the day

**Comment by SubJunk** [comment]
Awesome, thanks!

**Comment by Nadahar** [comment]
Please note that there are a number of issues I did not touch, I didn't even test test MovieDB functionality, I did not implement a save function for the ```MOVIEINFO.conf```.

There's a lot of small things in the code that I don't understand the intended purpose with, and the plugin seems to be written especially for polish users. I haven't even tested any other site than IMDB, and there's newer things like OMDB that should have been implemented.

There's also an issue with using Google for searching, as Google has some "anti scraping" policy in place that means that it doesn't take many lookups before you're served with a 503 http response and have to enter google.com and enter a captcha for google.com to continue working.

I've looked shortly on the different search API's, but they all require an API key, and Google only allows 100 searches a day before requiring you to buy access. Bing has a similar limit of 5000 searches a month, but using any of these would require the user to apply for and get his/her own API key - which I deep to be to much hazzle to be practical.

What's for sure is that a different search method to find the (IMDB) id should be implemented, as you won't have to lookup very many movies in a given time window before Google block you.

Https should probably also be implemented, as the only way to avoid google requiring it is to supply a very old user agent (as is currently done).

**Pull request merged**
